#' PCI patient survey data
#'
#' An artificial dataset containing patient characteristics and raw survey answers for the quality assurance domain PCI (percutaneous coronary intervention and coronary angiography).
#' Each data entry refers to one patient. Patient responses to survey items can take prespecified values between 0 and 100, where 0 generally refers to
#' "complete disagreement" or "not at all" and 100 refers to "full agreement" or "completely", depending on the item. All survey items
#' allow one or more special response categories for cases, in which the patient cannot or does not want to answer the survey question. These special
#' categories are "-99: no statement", "-98: I do not know or cannot remember", "-97: does not apply due to erroneous questionnaire filter" and "-96: question does not apply for me",
#' "-90: I could not do that, because of other reasons".
#'
#' @format A \code{data.frame} with 109 rows and 21 variables, which include 14 survey items:
#' \describe{
#'   \item{ID}{ID of data entry}
#'   \item{ID_LE}{ID of the patient's care provider}
#'   \item{Fragebogen}{Questionnaire type}
#'   \item{FB_Sent}{Date of questionnaire submission}
#'   \item{Gebdatum}{Date of birth}
#'   \item{Geschlecht}{Sex}
#'   \item{BMI}{Body mass index}
#'   \item{ARermutigtn}{Survey item: "Doctors encouraged me to ask questions during a consultation."}
#'   \item{ARernstn}{Survey item: "My concerns were taken seriously."}
#'   \item{ARrespektn}{Survey item: "Doctors treated me with respect."}
#'   \item{ARgelegenheitn}{Survey item: "I was given the opportunity to talk to a doctor, if I had any question."}
#'   \item{ARInfverstn}{Survey item: "The information I was given by doctors were comprehensible.}
#'   \item{ARfachwortn}{Survey item: "When talking to me doctors used medical terms that I did not comprehend."}
#'   \item{ARdeutschn}{Survey item: "Sometimes I cound not communicate with doctors, because they did not speak german."}
#'   \item{ARgesprochenn}{Survey item: "In my presence doctors talked about me as if I was not there."}
#'   \item{PAvoranginan}{Survey item: "Did you have any angina pectoris related problems or shortness of breath in advance of the procedure?"}
#'   \item{Anginaruhen}{Survey item: "Angina pectoris related problems: while resting."}
#'   \item{Anginaleichtn}{Survey item: "Angina pectoris related problems: during light everyday activities."}
#'   \item{PAvorbeeintrn}{Survey item: "How much was your everyday life affected by angina pectoris related problems or shortness of breath in advance of the procedure?"}
#'   \item{Anginaschwern}{Survey item: "Angina pectoris related problems: during heavy everyday activities."}
#'   \item{Anginaaussergn}{Survey item: "Angina pectoris related problems: during extraordinary physical efforts."}
#' }
"raw_data_pci"

#' PCI response category mappings
#'
#' A list of item category mapping rules applied to patient survey data for the quality assurance domain PCI (percutaneous coronary intervention and coronary angiography).
#'
#' @format A \code{list} containing two objects. The object \code{point_mappings}, which is itself a list containing
#' four unnamed list components specifying remapping rules for the answer categories.
#' Each of these four lists contains two objects:
#' \describe{
#'   \item{mapping}{A named \code{numeric} vector. The categories provided by the names are mapped onto the corresponding values between 0 and 100.}
#'   \item{felder}{A \code{character} vector providing the column names, which the \code{mapping} should be applied on.}
#' }
#' The second object \code{ausweichkategorien} is also a list containing specifications of non-informative values given through five lists of the form:
#' \describe{
#'   \item{value}{A \code{numeric} value, which should be mapped to NA}
#'   \item{felder}{A \code{character} vector providing the column names, for which the NA replacement should be applied.}
#' }
"mappings_pci"

#' PCI precomputations
#'
#' A list of precomputations applied to patient survey data for the quality assurance domain PCI (percutaneous coronary intervention and coronary angiography).
#' Each precomputation generates a new column within the data.
#'
#' @format A \code{list} containing two named precomputations. The component names will be used as name of the new data column
#' that will be generated by the precomputation. Each precomputation is itself a list containing 3 objects:
#' \describe{
#'   \item{expr}{The computation rule expression. This commonly refers to specific columns in the underlying data set and utilizes operators from the \code{iqtigfunctions} package.}
#'   \item{prototype}{An optional reference column. Value labels for the newly computed field are inherited from this reference column.}
#'   \item{labels}{(optional) A set of labels for the newly computed column values}
#' }
"precomputations_pci"


#' PCI quality indicator data base
#'
#' A list of quality indicator specifications for the quality assurance domain PCI (percutaneous coronary intervention and coronary angiography).
#'
#' @format A \code{list} containing a set of quality indicators. Each quality indicator is itself list containing 7 objects:
#' \describe{
#'   \item{Name}{The indicator name}
#'   \item{KN_ID}{The indicator ID}
#'   \item{GG}{The patient population ('Grundgesamtheit') to be included in the quality indicator, provided as a filter expression.}
#'   \item{RefArt}{The type of reference value. Possible values are "Fest" (fixed) or "Kein Referenzwert" (no reference value).}
#'   \item{RefVal}{The reference value to be used for indicator result classification}
#'   \item{RefOp}{The reference operator indicating, wether results greater (">=") or lower ("<=") than the reference value are desirable.}
#'   \item{Merkmale}{A \code{list} of attributes, that constitute the quality indicator. Each attribute is a list containing the attribute's \code{Name} and the underlying \code{Items}.}
#' }
"qidb_pci"
